name: Label PRs
on:
  pull_request:
    branches: [ "**" ]

# See .github/labeler.yml
jobs:
  Label_PR:
    runs-on: [ubuntu-latest]
    steps:
      - uses: srvaroa/labeler@545d0b4bc25708ea47d66b131bfc3de531086f5b
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
